### ISSUE TITLE
Polyphonic characters are wrong

### ISSUE THREAD

**Issue by RxxxxR** [gumblex/python-pinyin#1]
>>>from pypinyin import pinyin, Style
>>>pinyin("邓", style=Style.TONE, heteronym = True) #Correct result [['dèng']]
[['dèng', 'shān']]
>>>pinyin("晟", style=Style.TONE, heteronym = True) #Correct result [['chéng', 'shèng']]
[['chéng', 'shèng', 'jīng']]

**Comment by gumblex** [comment]
Please use upstream [mozillazg/python-pinyin](https://github.com/mozillazg/python-pinyin). This fork is unmaintained.
